name: "Open WebUI"
version: "0.6.31"
slug: "open-webui"
description: "Open WebUI is an extensible, self-hosted interface for AI that adapts to your workflow, all while operating entirely offline."
url: https://openwebui.com
arch:
  - amd64
init: false
map:
  - type: addon_config
    read_only: False
    path: /app/backend/data
  - type: data
    path: /root/.ollama
legacy: True
host_network: True
options:
  port: 8084
  env_vars: []
schema:
  port: port
  env_vars:
    - name: match(^[A-Z0-9_]+$)
      value: str
startup: application
